### ISSUE TITLE
Installation fails - ez_setup is required

### ISSUE THREAD

**Issue by mfiers** [daler/biomartpy#1]
Installation fails when ez_setup is not installed (see below).

maybe add this as a requirement?

cheers
Mark

```
Downloading/unpacking biomartpy
  Downloading biomartpy-0.1.tar.gz
  Running setup.py (path:/Users/u0089478/.virtualenvs/test/build/biomartpy/setup.py) egg_info for package biomartpy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/u0089478/.virtualenvs/test/build/biomartpy/setup.py", line 1, in <module>
        import ez_setup
    ImportError: No module named ez_setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/u0089478/.virtualenvs/test/build/biomartpy/setup.py", line 1, in <module>

    import ez_setup

ImportError: No module named ez_setup
```

**Comment by daler** [comment]
I just updated it in 3e9ead9c7e46fbb0b5223f7f1eccbef5365c3e99 and on PyPI, can you give it another shot?

**Comment by mfiers** [comment]
Cool. Seems to work now. Thanks.
